package com.scanity.kalsel;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.provider.Settings;import android.text.*;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import org.json.*;import com.google.zxing.*;import com.google.zxing.common.BitMatrix;

public class MainActivity extends Activity {
    LinearLayout root,content; ArrayList<JSONObject> members=new ArrayList<>(); SharedPreferences prefs; int red=Color.rgb(230,0,0),black=Color.rgb(8,8,8),gray=Color.rgb(245,245,245); JSONObject editing; ImageView editPhoto; String currentPhoto="";
    final int PICK_PHOTO=501;
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("scanity",0);load();if(!prefs.getBoolean("intro",false)){prefs.edit().putBoolean("intro",true).apply();}showHome();}
    TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(black);t.setPadding(18,12,18,12);return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setAllCaps(false);b.setBackgroundColor(red);return b;}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(8,0,8,0);bar.setBackgroundColor(black);TextView h=tv(title,19);h.setTextColor(Color.WHITE);h.setTypeface(null,1);bar.addView(h,new LinearLayout.LayoutParams(0,60,1));root.addView(bar);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(16,14,16,24);ScrollView sc=new ScrollView(this);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    ImageView logo(){ImageView im=new ImageView(this);im.setImageResource(R.drawable.scanity_logo);im.setAdjustViewBounds(true);im.setPadding(0,5,0,12);return im;}
    void showHome(){base("SCANITY KALSEL");content.addView(logo());TextView title=tv("SIGRA CALYA COMMUNITY\nCHAPTER KALIMANTAN SELATAN",20);title.setTypeface(null,1);content.addView(title);content.addView(tv("Sharing • Fun • Touring • Modified",14));
        LinearLayout stats=new LinearLayout(this);stats.setPadding(0,10,0,10);stats.addView(card("ANGGOTA",String.valueOf(members.size())),new LinearLayout.LayoutParams(0,-2,1));stats.addView(card("AKTIF",String.valueOf(countActive())),new LinearLayout.LayoutParams(0,-2,1));stats.addView(card("KORWIL","4"),new LinearLayout.LayoutParams(0,-2,1));content.addView(stats);
        Button a=btn("👥  Data Anggota");a.setOnClickListener(v->showMembers());content.addView(a);Button c=btn("➕  Tambah Anggota");c.setOnClickListener(v->loginThen(()->memberForm(null)));content.addView(c);Button k=btn("📍  Data Korwil");k.setOnClickListener(v->korwil());content.addView(k);Button e=btn("📅  Kegiatan & Pengumuman");e.setOnClickListener(v->events());content.addView(e);Button backup=btn("💾  Cadangkan / Pulihkan Data");backup.setOnClickListener(v->backupMenu());content.addView(backup);Button admin=btn("⚙️  Admin / Pengaturan");admin.setOnClickListener(v->loginThen(()->adminMenu()));content.addView(admin);}
    LinearLayout card(String a,String b){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER);l.setPadding(4,8,4,8);l.setBackgroundColor(gray);TextView x=tv(a,11);x.setGravity(Gravity.CENTER);TextView y=tv(b,22);y.setTypeface(null,1);y.setGravity(Gravity.CENTER);l.addView(x);l.addView(y);return l;}
    int countActive(){int n=0;for(JSONObject m:members)if(m.optString("status","Aktif").equalsIgnoreCase("Aktif"))n++;return n;}
    void showMembers(){base("DATA ANGGOTA");EditText search=e("Cari nama / ID / plat nomor / korwil...","");content.addView(search);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);Runnable render=()->{list.removeAllViews();String q=search.getText().toString().toLowerCase();for(JSONObject m:members){String s=(m.optString("name")+" "+m.optString("id")+" "+m.optString("plate")+" "+m.optString("korwil")).toLowerCase();if(!s.contains(q))continue;LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setPadding(10,8,10,8);row.setBackgroundColor(gray);ImageView p=new ImageView(this);p.setImageURI(uri(m.optString("photo")));p.setImageResource(R.drawable.scanity_logo);String ph=m.optString("photo");if(!ph.isEmpty())try{p.setImageURI(Uri.parse(ph));}catch(Exception ex){}row.addView(p,new LinearLayout.LayoutParams(70,70));TextView x=tv(m.optString("id")+" • "+m.optString("name")+"\n"+m.optString("vehicle")+" • "+m.optString("plate")+"\n"+m.optString("korwil")+" • "+m.optString("status","Aktif"),15);row.addView(x,new LinearLayout.LayoutParams(0,-2,1));row.setOnClickListener(v->detail(m));list.addView(row);Space sp=new Space(this);list.addView(sp,new LinearLayout.LayoutParams(1,7));}};search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){render.run();}public void afterTextChanged(Editable e){}});render.run();Button add=btn("➕ Tambah Anggota");add.setOnClickListener(v->loginThen(()->memberForm(null)));content.addView(add);Button back=btn("Kembali");back.setOnClickListener(v->showHome());content.addView(back);}
    Uri uri(String s){return s==null||s.isEmpty()?null:Uri.parse(s);}
    EditText e(String h,String v){EditText x=new EditText(this);x.setHint(h);x.setText(v);x.setTextSize(15);x.setPadding(10,10,10,10);return x;}
    void memberForm(JSONObject old){editing=old;currentPhoto=old==null?"":old.optString("photo","");base(old==null?"TAMBAH ANGGOTA":"EDIT ANGGOTA");editPhoto=new ImageView(this);editPhoto.setImageResource(R.drawable.scanity_logo);editPhoto.setAdjustViewBounds(true);content.addView(editPhoto,new LinearLayout.LayoutParams(-1,180));if(old!=null&&!old.optString("photo").isEmpty())try{editPhoto.setImageURI(Uri.parse(old.optString("photo")));}catch(Exception ignored){}Button photo=btn("📷 Pilih Foto Anggota");photo.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_PHOTO);});content.addView(photo);
        EditText id=e("ID Anggota",old==null?nextId():old.optString("id"));EditText name=e("Nama Lengkap",old==null?"":old.optString("name"));EditText nick=e("Nama Panggilan",old==null?"":old.optString("nick"));EditText phone=e("Nomor WhatsApp",old==null?"":old.optString("phone"));EditText plate=e("Nomor Polisi",old==null?"":old.optString("plate"));EditText vehicle=e("Kendaraan (Sigra/Calya)",old==null?"":old.optString("vehicle"));EditText year=e("Tahun Kendaraan",old==null?"":old.optString("year"));EditText kor=e("Korwil (Tatanko/Babam/Banam/Balat)",old==null?"":old.optString("korwil"));EditText status=e("Status (Aktif/Nonaktif)",old==null?"Aktif":old.optString("status","Aktif"));for(EditText x:new EditText[]{id,name,nick,phone,plate,vehicle,year,kor,status})content.addView(x);Button save=btn("💾 Simpan Data");save.setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){name.setError("Nama wajib diisi");return;}try{JSONObject m=old==null?new JSONObject():old;m.put("id",id.getText().toString().trim());m.put("name",name.getText().toString().trim());m.put("nick",nick.getText().toString().trim());m.put("phone",phone.getText().toString().trim());m.put("plate",plate.getText().toString().trim());m.put("vehicle",vehicle.getText().toString().trim());m.put("year",year.getText().toString().trim());m.put("korwil",kor.getText().toString().trim());m.put("status",status.getText().toString().trim());m.put("photo",currentPhoto);if(old==null)members.add(m);save();Toast.makeText(this,"Data anggota tersimpan",Toast.LENGTH_SHORT).show();showMembers();}catch(Exception ex){Toast.makeText(this,"Gagal menyimpan",Toast.LENGTH_SHORT).show();}});content.addView(save);Button back=btn("Batal");back.setOnClickListener(v->showMembers());content.addView(back);}
    String nextId(){return String.format(Locale.US,"SCN-%03d",members.size()+1);}
    void detail(JSONObject m){base("KARTU ANGGOTA");content.addView(logo());ImageView p=new ImageView(this);p.setAdjustViewBounds(true);p.setImageResource(R.drawable.scanity_logo);if(!m.optString("photo").isEmpty())try{p.setImageURI(Uri.parse(m.optString("photo")));}catch(Exception ignored){}content.addView(p,new LinearLayout.LayoutParams(-1,200));TextView x=tv("ID: "+m.optString("id")+"\nNama: "+m.optString("name")+" ("+m.optString("nick")+")\nWhatsApp: "+m.optString("phone")+"\nKendaraan: "+m.optString("vehicle")+"\nNo. Polisi: "+m.optString("plate")+"\nTahun: "+m.optString("year")+"\nKorwil: "+m.optString("korwil")+"\nStatus: "+m.optString("status","Aktif"),17);content.addView(x);Button qr=btn("▣  Tampilkan QR Code");qr.setOnClickListener(v->showQR(m));content.addView(qr);Button edit=btn("✏️  Edit Data");edit.setOnClickListener(v->loginThen(()->memberForm(m)));content.addView(edit);Button del=btn("🗑️  Hapus Anggota");del.setOnClickListener(v->loginThen(()->confirmDelete(m)));content.addView(del);Button back=btn("Kembali");back.setOnClickListener(v->showMembers());content.addView(back);}
    void confirmDelete(JSONObject m){new AlertDialog.Builder(this).setTitle("Hapus anggota?").setMessage(m.optString("name")).setNegativeButton("Batal",null).setPositiveButton("Hapus",(d,w)->{members.remove(m);save();showMembers();}).show();}
    void showQR(JSONObject m){base("QR KARTU ANGGOTA");TextView h=tv(m.optString("name")+"\n"+m.optString("id"),20);h.setGravity(Gravity.CENTER);h.setTypeface(null,1);content.addView(h);ImageView im=new ImageView(this);try{BitMatrix bm=new MultiFormatWriter().encode(m.toString(),BarcodeFormat.QR_CODE,700,700);Bitmap b=Bitmap.createBitmap(700,700,Bitmap.Config.ARGB_8888);for(int y=0;y<700;y++)for(int x=0;x<700;x++)b.setPixel(x,y,bm.get(x,y)?Color.BLACK:Color.WHITE);im.setImageBitmap(b);}catch(Exception ex){content.addView(tv("QR tidak dapat dibuat",16));}content.addView(im,new LinearLayout.LayoutParams(-1,700));Button back=btn("Kembali");back.setOnClickListener(v->detail(m));content.addView(back);}
    void korwil(){base("DATA KORWIL");String[] a={"Korwil Tatanko","Korwil Babam","Korwil Banam","Korwil Balat"};for(String s:a){int n=0;for(JSONObject m:members)if(m.optString("korwil").equalsIgnoreCase(s.replace("Korwil ",""))||m.optString("korwil").equalsIgnoreCase(s))n++;content.addView(tv("📍 "+s+"\nAnggota: "+n,18));}Button back=btn("Kembali");back.setOnClickListener(v->showHome());content.addView(back);}
    void events(){base("KEGIATAN & PENGUMUMAN");content.addView(tv("📢 PENGUMUMAN",20));content.addView(tv("Informasi resmi kegiatan SCANITY Kalsel dapat ditambahkan melalui menu Admin.",15));content.addView(tv("📅 KEGIATAN",20));content.addView(tv(prefs.getString("events","Belum ada kegiatan yang ditambahkan."),15));if(prefs.getBoolean("admin",false)){Button edit=btn("✏️ Edit Kegiatan / Pengumuman");edit.setOnClickListener(v->editEvents());content.addView(edit);}Button back=btn("Kembali");back.setOnClickListener(v->showHome());content.addView(back);}
    void editEvents(){base("EDIT KEGIATAN");EditText x=e("Tulis kegiatan/pengumuman",prefs.getString("events",""));x.setMinLines(8);content.addView(x);Button s=btn("Simpan");s.setOnClickListener(v->{prefs.edit().putString("events",x.getText().toString()).apply();events();});content.addView(s);}
    void adminMenu(){base("ADMIN / PENGATURAN");content.addView(tv("Admin aktif",18));Button pass=btn("🔑 Ganti Password Admin");pass.setOnClickListener(v->changePass());content.addView(pass);Button logout=btn("Keluar Admin");logout.setOnClickListener(v->{prefs.edit().putBoolean("admin",false).apply();showHome();});content.addView(logout);Button back=btn("Kembali");back.setOnClickListener(v->showHome());content.addView(back);}
    void loginThen(Runnable r){final LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText u=e("Username","admin");EditText p=e("Password","");p.setInputType(129);box.addView(u);box.addView(p);new AlertDialog.Builder(this).setTitle("Login Admin").setView(box).setNegativeButton("Batal",null).setPositiveButton("Masuk",(d,w)->{String user=u.getText().toString();String pw=p.getText().toString();String saved=prefs.getString("password","scanity2026");if(user.equals("admin")&&pw.equals(saved)){prefs.edit().putBoolean("admin",true).apply();r.run();}else Toast.makeText(this,"Username/password salah",Toast.LENGTH_SHORT).show();}).show();}
    void changePass(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText p=e("Password baru","");p.setInputType(129);box.addView(p);new AlertDialog.Builder(this).setTitle("Ganti Password").setView(box).setNegativeButton("Batal",null).setPositiveButton("Simpan",(d,w)->{if(p.getText().length()<6){Toast.makeText(this,"Minimal 6 karakter",Toast.LENGTH_SHORT).show();return;}prefs.edit().putString("password",p.getText().toString()).apply();Toast.makeText(this,"Password diperbarui",Toast.LENGTH_SHORT).show();}).show();}
    void backupMenu(){new AlertDialog.Builder(this).setTitle("Cadangan Data").setItems(new String[]{"Bagikan backup JSON","Pulihkan dari file JSON"},(d,w)->{if(w==0)shareBackup();else restoreBackup();}).show();}
    void shareBackup(){try{String raw=prefs.getString("members","[]");Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,raw);i.putExtra(Intent.EXTRA_SUBJECT,"Backup Data SCANITY Kalsel");startActivity(Intent.createChooser(i,"Bagikan backup"));}catch(Exception ex){}}
    void restoreBackup(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,777);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==PICK_PHOTO){try{getContentResolver().takePersistableUriPermission(d.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION);editPhoto.setImageURI(d.getData());currentPhoto=d.getData().toString();if(editing!=null)editing.put("photo",currentPhoto);}catch(Exception ignored){}}else if(r==777){try{InputStream in=getContentResolver().openInputStream(d.getData());BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line);JSONArray a=new JSONArray(sb.toString());members.clear();for(int j=0;j<a.length();j++)members.add(a.getJSONObject(j));save();showMembers();Toast.makeText(this,"Backup dipulihkan",Toast.LENGTH_SHORT).show();}catch(Exception ex){Toast.makeText(this,"File backup tidak valid",Toast.LENGTH_SHORT).show();}}}
    void load(){try{JSONArray a=new JSONArray(prefs.getString("members","[]"));for(int i=0;i<a.length();i++)members.add(a.getJSONObject(i));}catch(Exception ignored){}}
    void save(){try{JSONArray a=new JSONArray();for(JSONObject m:members)a.put(m);prefs.edit().putString("members",a.toString()).apply();}catch(Exception ignored){}}
}
